# NOTE(mattt): This file is currently not used, see all_components.yml instead.
---
  - name: rpc-product-1
    versions:
      - version: 0.0.1
        components:
          - name: rpc-component-1
            repo: https://github.com/mattt416/rpc-component-1
            version: master
          - name: rpc-component-2
            repo: https://github.com/mattt416/rpc-component-2
            version: master
