---
products:
#  - name: rpc-openstack-swift
#    components:
#      - name: rpc-openstack
#        version: 1.2.3
#      - name: rpc-maas
#        version: 1.2.3
#  - name: rpc-openstack-ceph
#    components:
#      - name: rpc-openstack
#        version: 1.2.3
#      - name: rpc-maas
#        version: 1.2.3
#      - name: rpc-ceph
#        version: 1.2.3
#  - name: rpc-openstack-hummingbird
#    components:
#      - name: rpc-openstack
#        version: 1.2.3
#      - name: rpc-maas
#        version: 1.2.3
#      - name: rpc-hummingbird
#        version: 1.2.3
#  - name: ceph
#    components:
#      - name: rpc-ceph
#        version: 1.2.3
#      - name: rpc-maas
#        version: 1.2.3
#  - name: hummingbird
#    components:
#      - name: rpc-hummingbird
#        version: 1.2.3
#      - name: rpc-maas
#        version: 1.2.3
#      - name: rpc-openstack # required for auth (to be verified)
#        version: 1.2.3
  - name: dummy
    components:
      - name: rpc-component-1
        repo: https://github.com/mattt416/rpc-component-1
        version: master
      - name: rpc-component-2
        repo: https://github.com/mattt416/rpc-component-2
        version: master
